### ISSUE TITLE
Integration with RobertGregg/FGES.jl

### ISSUE THREAD

**Issue by mschauer** [mschauer/CausalInference.jl#77]
@RobertGregg I create this issue to see how can integrate your FGES algorithm implementation https://github.com/RobertGregg/FGES.jl

**Comment by mschauer** [comment]
Found to functions which do about the same thing:

https://github.com/RobertGregg/FGES.jl/blob/3d396135f841d5e2f209eacb4d001194f5805fb9/src/graphStructure.jl#L234

https://github.com/mschauer/CausalInference.jl/blob/531b0a49f74c9462717138191f4662c69a939ab7/src/graphs.jl#L11

That should help getting acquainted with the different interfaces (CausalInference uses directed Graphs.jl, with PDAG represented as DAGs with both the forward and the backward edge added, and FGES uses their own graph structure)

**Comment by RobertGregg** [comment]
Fantastic thank you for starting this thread. 

Switching over to Graphs.jl using a DiGraph should be really easy because I borrowed a lot of naming conventions from Graphs.jl. I think at the time I didn't realize one edge could have multiple directions in a DiGraph.

It does look like `has_a_path` and `isblocked` are very similar just with the logic reversed. Does `has_a_path` look at semi-directed paths (e.g. would src → x₁ - x₂ → dest be valid?). 

Would it make sense to put some of the functions used by multiple algorithms into a common file? For example, the `has_a_path` and `is_parent` functions can be used by both fges and fci. Maybe the "graph.jl" file or a new one?

Do you have a specific naming convention for functions/structures? It looks like you generally use snake_case which I can adopt.

**Comment by mschauer** [comment]
> Does `has_a_path` look at semi-directed paths (e.g. would src → x₁ - x₂ → dest be valid?).

Yes, as undirected is represented by both edges just
following forward edges just works

**Comment by mschauer** [comment]
2. Yes, I am happy with the experience of just using digraphs from Graphs.jl and would recommmend that, I am also happy to structure the code more it has grown organically and could be refactored. And I loosely follow the Julia style of snake_case with underscore omitted sometimes for readability, I.e “getindex”

**Comment by RobertGregg** [comment]
So I forked the repository and got FGES running without any errors. However, I'm not getting the same results as before from testing. I think it might be due to `edges(graph)` iterating over both `x => y` and `y => x` when x-y is undirected. It could also be something silly like a typo 😵 

Just out curiosity, what does "Package Extensions" do? I noticed it in the main CausalInference.jl module

**Comment by mschauer** [comment]
> `edges(graph)` iterating over both `x => y` and `y => x` when x-y is undirected. I

Yes, exactly!

> Just out curiosity, what does "Package Extensions" do? 

The code to plot graphs depends on the plotting package, we use PackageExtension to load the right code for the users plotting package.

**Comment by sumantrak** [comment]
I am happy to contribute, but my progress will be a bit slow.
